Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # Debian VM для Asterisk
  config.vm.define "asterisk" do |asterisk|
    asterisk.vm.box = "debian/bookworm64"
    asterisk.vm.hostname = 'asterisk'
    asterisk.vm.network 'private_network', ip: "192.168.56.101"
    asterisk.vm.provision 'shell', path: "../asterisk/setup.sh"
  end

  # Ubuntu VM для PostgreSQL
  config.vm.define "postgresql" do |db|
    db.vm.box = 'ubuntu/focal64'
    db.vm.hostname = 'postgresql'
    db.vm.network 'private_network', ip: '192.168.56.102'
    db.vm.provision 'shell', path: '../postgresql/setup.sh'
  end
end